cc_library(
    name = "kernel",
    srcs = [
        "exit.c", "fork.c", "mktime.c", "panic.c", "printk.c", "sched.c", "signal.c", "sys.c", "traps.c", "vsprintf.c", "system_call.s", "asm.s"
    ],
    includes = ["../include"],
    visibility = ["//visibility:public"],
)

