cc_library(
    name = "fs",
    srcs = [
        "bitmap.c", "block_dev.c", "buffer.c", "char_dev.c", "exec.c", "fcntl.c", "file_dev.c", "file_table.c", "inode.c", "ioctl.c", "namei.c", "open.c", "pipe.c", "read_write.c", "stat.c", "super.c", "truncate.c"
    ],
    includes = ["../include"],
    visibility = ["//visibility:public"],
)

