cc_library(
    name = "lib",
    srcs = [
        "close.c", "ctype.c", "dup.c", "errno.c", "execve.c", "malloc.c", "open.c", "setsid.c", "string.c", "wait.c", "write.c", "_exit.c"
    ],
    includes = ["../include"],
    visibility = ["//visibility:public"],
)

